import java.util.Scanner;
import java.util.Random;

public class GuessNumber {
    public static void main(String[] args) {
        Scanner sc=new Scanner(System.in);
        Random randomNum=new Random();
        int maxTries=7;
        boolean result=false;

        //randomNumber generated by comp
        int comp=randomNum.nextInt(100)+1;
        System.out.println();
        System.out.println("-------== Welcome to the Game! ==------\n");
        System.out.println("I have a number in mind between 1 to 100.");
        System.out.println("Come on, guess it!  @AttemptLimit: "+maxTries);

        //number input by user and result
        while (maxTries>0 && !result) {
            int user=sc.nextInt();
            maxTries--;
            if(maxTries==0){
                break;
            }

            if(comp==user){
                System.out.println("\nCongratulaion!, you won.");
                System.out.println("Score: "+(maxTries+3)+"/10");
                result=true;
            }
            else if(comp<user){
                System.out.println("\nGuess, little low.");
                
            }else{
                System.out.println("\nGuess, little high.");
                
            }
            System.out.println("Attempt Left: "+maxTries);
        }
        if(!result){
            System.out.println("\nOops, you lost the game.");
            System.out.println("Score: 0/10");
        }  
        sc.close(); 
    }
}